Feature/req0
daruz14/datascope pull request #1
Opened 2024-01-07 17:52 UTC by daruz14

### Contexto:
Se necesita poder tener una aplicación que permita crear/agendar eventos entre distintos usuarios.

### Cambios Realizados:
- Se crea versión base de los modelos Users, Events y Company
- Se establece la relación N-N entre Users y Events
- Se establece la relación 1-N entre Users y Company
- Se modifica la vista base inicial de eventos para que pueda agregar usuarios
- Se agrega el uso de la gema `devise` para hacer manejo de usuarios con autentificación

### Consideraciones Técnicas:
- Se agrega el uso de las gemas `devise` y `httparty`.

2024-01-08 13:32 UTC, daruz14 commented
Hola @jjaguillon! te etiqueto en esta PR que es el código base sobre el cuál desarrollaré los REQ1-REQ7, para que lo puedas ver cuando tengas tiempito 🙏🏾 . Gracias! 🙌🏾

2024-01-08 13:33 UTC, jjaguillon requested changes
Nice one @daruz14! Ya tienes el codebase y los modelos estan correctos. 

Mi único comentario respecto a lo que llevas es que tanto los Usuarios como los Eventos no estan filtrados por compañía en el índice. Te hace sentido tener este filtro incorporado en el controlador?

Quedo atento!

2024-01-09 14:22 UTC, daruz14 commented
Hola @jjaguillon! acabo de actualizar el PR con unos cambios en el controlador para ya realizar el filtro por compañia y también lo agregué en los eventos! 🤝 😄

2024-01-09 21:51 UTC, daruz14 commented
@jjaguillon  👀

2024-01-10 14:25 UTC, jjaguillon approved these changes
LGTM!

![](https://media4.giphy.com/media/l3V0wpHLf2qOEwegE/giphy.gif?cid=ecf05e47jgmn1lxkg5lwu6o4iha0m2iyvrb8fqznbvw7mx00&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2024-01-10 14:49 UTC, merged